[features]
seeds = false
skip-lint = false
[programs.localnet]
liberte_program = "H5JnjsAu4yYNnY3fHxTTA2ySnYqqf2uAWK2QHJKPBMho"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hadi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
